### ISSUE TITLE
Feature: track games and add game history to player profile

### ISSUE THREAD

**Issue by andrew-fleming** [dustinstacy/triple-triad-reactjs#119]

**Comment by dustinstacy** [comment]
Also never formally thanked you for this one as well! 
Huge benefit to devs and users.
Another excellent idea that'll be in the mix before long.

**Comment by andrew-fleming** [comment]
Haha it's my pleasure. I can't wait!

**Comment by dustinstacy** [comment]
So I realize now the suggestion also included adding it to the player's profile. May be a good thing that I left that part out because we can filter the BattleLogs database by the user's _id since that will be present in any log they are a part of. This prevents the bloating of an already large User schema and keeps the DB slim.
